AWSTemplateFormatVersion: '2010-09-09'
Description: Sample S3 Bucket from GitHub Actions

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-gh-actions-bucket-unique-9876543210
