AWSTemplateFormatVersion: '2010-09-09'
Description: Secure S3 Bucket from GitHub Actions

Resources:
  MySecureBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-gh-secure-bucket-1234567890-avi
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
