AWSTemplateFormatVersion: '2010-09-09'
Description: Insecure S3 Bucket for testing cfn-nag failure

Resources:
  InsecureS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cfn-nag-test-bucket-123456
