AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket with public read ACL (Triggers FAIL in cfn-nag) 

Resources:
  InsecurePublicBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-public-cfn-nag-bucket-9876543210-unq-demo
